El objetivo de este proyecto en general es de garantizarle a nuestro cliente según nuestros estudios una excelentge información sobre en qué estados de Estados Unidos es recomendable invertir en una vivienda, teniendo en cuenta si en estas zonas se encuentra en una posible recesión.

El PRODUCTO INTERNO BRUTO en un país  es una medida del valor de la actividad económica de un país, que permite conocer el nivel de producción de bienes y servicios de una nación en un período de tiempo específico. usualmente, este indicador se conoce con frecuencia trimestral y anual. También esta medición nos puede advertir de una posible reseción económica, ya que técnicamente se dice que en una zona donde este PIB decrezca dos semestres consecutivos se dice que puede haber dicha reseción.

In [1]:
import pandas as pd 
import numpy as np

Union de bases de datos de tablas dadas Dataset_price_rent

Esta tabla que muestro acontinuación es la unión de varias bases proporcionadas por el cliente, lo que hicimos fue unir aquellas tablas comunes en información, ya en otro código mostramos dicho procedimiento.

In [2]:
data=pd.read_csv("Dataset_price_rent_roi_alltypes.csv")

In [3]:
data.head()

       region     date     price  rent property_type  roi
0  California  2010-02  231512.0   NaN      1Bedroom  NaN
1  California  2010-03  230640.0   NaN      1Bedroom  NaN
2  California  2010-04  230508.0   NaN      1Bedroom  NaN
3  California  2010-05  230649.0   NaN      1Bedroom  NaN
4  California  2010-06  229228.0   NaN      1Bedroom  NaN

Es muy importante comprobar que esten los 51 Estados a estudiar:

Comprobamos que estan los 51 Estados

In [4]:
listaRegion=list(data.region.unique())

In [5]:
len(listaRegion)

51

In [6]:
listaRegion

['California',
 'Texas',
 'New York',
 'Florida',
 'Illinois',
 'Pennsylvania',
 'Ohio',
 'Michigan',
 'Georgia',
 'North Carolina',
 'New Jersey',
 'Virginia',
 'Washington',
 'Massachusetts',
 'Indiana',
 'Arizona',
 'Tennessee',
 'Missouri',
 'Maryland',
 'Wisconsin',
 'Minnesota',
 'Colorado',
 'Alabama',
 'South Carolina',
 'Louisiana',
 'Kentucky',
 'Oregon',
 'Oklahoma',
 'Connecticut',
 'Iowa',
 'Mississippi',
 'Arkansas',
 'Kansas',
 'Utah',
 'Nevada',
 'New Mexico',
 'West Virginia',
 'Nebraska',
 'Idaho',
 'Hawaii',
 'Maine',
 'New Hampshire',
 'Rhode Island',
 'Montana',
 'Delaware',
 'South Dakota',
 'Alaska',
 'North Dakota',
 'Vermont',
 'District of Columbia',
 'Wyoming']

En las bases de datos que nos dieron nuestros clientes, la informacion sobre el PIB estaba muy confusa, muy incompleta, debido a esto nos tocó buscar información ajena en la red       ( esto recomendado por el cliente ) sobre este índice, obteniéndola en una API ( BEA Data Application Programming Interface (API)) cuya dirección url: https://apps.bea.gov/api/signup/

In [7]:
PIB=pd.read_csv("PIBxEstados2.csv")

En esta base de datos tengo los valores de la variación del PIB con respecto al trimestre anterior.
Tenemos información desde el 2005 hasta principios del 2022. 
Debemos tomar una desición sobre qué rango de años vamos a tomar, según la información que tengamos a nivel general, ya que debemos medir otros KPI adicionales al proyecto. 
Una de las primeros resultados que quise mostrar con esta información es la de los períodos donde ha habido dos trimestres consecutivos en valores del PIB negativos, a continuación están los resultados:

me aseguro de hacer duplicados de las bases

In [8]:
a = PIB.copy()

elimino las columnas(temporalmente) para que solo me queden columnas con campos numéricos para poder mostrar en que períodos encontramos dos trimestres consecutivos con valores negativos.

In [9]:
a.drop(["GeoFips","GeoName"],axis=1,inplace=True)

In [10]:
b=a.copy()

In [11]:
b.drop(["2005:Q1-:Q2"],axis=1,inplace=True)

Luego creamos 2 arrays para poder ir comparando dos trimestres consecutivos, este nos mostrará la información que queremos, por ahora solo nos muesta los períodos, más adelante mostraremos mejor esta información por Estados.

In [12]:
columns_namesA=a.columns.values
columns_namesB=b.columns.values

In [13]:
columns_namesA

array(['2005:Q1-:Q2', '2005:Q2-:Q3', '2005:Q3-:Q4', '2005:Q4-2006:Q1',
       '2006:Q1-:Q2', '2006:Q2-:Q3', '2006:Q3-:Q4', '2006:Q4-2007:Q1',
       '2007:Q1-:Q2', '2007:Q2-:Q3', '2007:Q3-:Q4', '2007:Q4-2008:Q1',
       '2008:Q1-:Q2', '2008:Q2-:Q3', '2008:Q3-:Q4', '2008:Q4-2009:Q1',
       '2009:Q1-:Q2', '2009:Q2-:Q3', '2009:Q3-:Q4', '2009:Q4-2010:Q1',
       '2010:Q1-:Q2', '2010:Q2-:Q3', '2010:Q3-:Q4', '2010:Q4-2011:Q1',
       '2011:Q1-:Q2', '2011:Q2-:Q3', '2011:Q3-:Q4', '2011:Q4-2012:Q1',
       '2012:Q1-:Q2', '2012:Q2-:Q3', '2012:Q3-:Q4', '2012:Q4-2013:Q1',
       '2013:Q1-:Q2', '2013:Q2-:Q3', '2013:Q3-:Q4', '2013:Q4-2014:Q1',
       '2014:Q1-:Q2', '2014:Q2-:Q3', '2014:Q3-:Q4', '2014:Q4-2015:Q1',
       '2015:Q1-:Q2', '2015:Q2-:Q3', '2015:Q3-:Q4', '2015:Q4-2016:Q1',
       '2016:Q1-:Q2', '2016:Q2-:Q3', '2016:Q3-:Q4', '2016:Q4-2017:Q1',
       '2017:Q1-:Q2', '2017:Q2-:Q3', '2017:Q3-:Q4', '2017:Q4-2018:Q1',
       '2018:Q1-:Q2', '2018:Q2-:Q3', '2018:Q3-:Q4', '2018:Q4-2019:Q1',
       '2019:Q1-:Q2', '2019:Q2-:Q3', '2019:Q3-:Q4', '2019:Q4-2020:Q1',
       '2020:Q1-:Q2', '2020:Q2-:Q3', '2020:Q3-:Q4', '2020:Q4-2021:Q1',
       '2021:Q1-:Q2', '2021:Q2-:Q3', '2021:Q3-:Q4', '2021:Q4-2022:Q1',
       '2022:Q1-:Q2'], dtype=object)

Este for me da los dos trimestres consecutivos en negativo

In [14]:
for c in range(68):
    d=0
    #c=0
    i=0
    while i<59:
        if PIB[columns_namesA[c]][d]<0 and PIB[columns_namesA[c+1]][d]<0:
            print(columns_namesA[c])
            print(PIB[columns_namesA[c]][d],PIB[columns_namesA[c+1]][d])
            print("indice: ",i)
            d+=1
            i+=1
            
        else:
            d+=1
            i+=1

2006:Q1-:Q2
-11.7 -1.2
indice:  36
2006:Q2-:Q3
-1.5 -3.6
indice:  7
2006:Q2-:Q3
-1.2 -1.2
indice:  36
2006:Q3-:Q4
-0.3 -3.6
indice:  3
2006:Q3-:Q4
-1.3 -12.4
indice:  18
2007:Q2-:Q3
-7.3 -3.5
indice:  7
2007:Q3-:Q4
-3.5 -4.4
indice:  7
2007:Q3-:Q4
-1.4 -6.8
indice:  9
2007:Q3-:Q4
-0.1 -0.6
indice:  19
2007:Q3-:Q4
-7.6 -7.3
indice:  22
2007:Q4-2008:Q1
-6.8 -2.4
indice:  9
2007:Q4-2008:Q1
-1.5 -0.4
indice:  14
2007:Q4-2008:Q1
-3.6 -1.5
indice:  15
2007:Q4-2008:Q1
-7.3 -3.2
indice:  22
2007:Q4-2008:Q1
-8.2 -2.5
indice:  28
2008:Q1-:Q2
-6.2 -10.0
indice:  6
2008:Q1-:Q2
-2.4 -3.7
indice:  9
2008:Q1-:Q2
-0.4 -1.9
indice:  14
2008:Q1-:Q2
-1.5 -3.0
indice:  15
2008:Q1-:Q2
-3.2 -5.7
indice:  22
2008:Q1-:Q2
-1.8 -0.5
indice:  29
2008:Q1-:Q2
-5.1 -4.6
indice:  41
2008:Q1-:Q2
-0.1 -3.8
indice:  51
2008:Q2-:Q3
-1.5 -10.0
indice:  2
2008:Q2-:Q3
-10.0 -15.4
indice:  6
2008:Q2-:Q3
-3.7 -7.8
indice:  9
2008:Q2-:Q3
-2.4 -2.5
indice:  11
2008:Q2-:Q3
-1.9 -8.0
indice:  14
2008:Q2-:Q3
-3.0 -6.8
indice:  15
2008:Q2-:Q3
-0.7 -9.6
indice:  16
2008:Q2-:Q3
-3.5 -7.3
indice:  17
2008:Q2-:Q3
-1.9 -2.9
indice:  21
2008:Q2-:Q3
-5.7 -4.3
indice:  22
2008:Q2-:Q3
-2.1 -11.4
indice:  27
2008:Q2-:Q3
-0.5 -4.3
indice:  29
2008:Q2-:Q3
-2.5 -11.4
indice:  35
2008:Q2-:Q3
-4.6 -13.8
indice:  41
2008:Q2-:Q3
-3.8 -6.4
indice:  51
2008:Q2-:Q3
-1.0 -6.9
indice:  53
2008:Q3-:Q4
-8.3 -3.9
indice:  0
2008:Q3-:Q4
-25.7 -19.3
indice:  1
2008:Q3-:Q4
-10.0 -11.4
indice:  2
2008:Q3-:Q4
-11.3 -1.5
indice:  4
2008:Q3-:Q4
-10.2 -4.2
indice:  5
2008:Q3-:Q4
-7.8 -3.7
indice:  9
2008:Q3-:Q4
-7.7 -2.0
indice:  10
2008:Q3-:Q4
-2.5 -3.3
indice:  11
2008:Q3-:Q4
-7.9 -7.3
indice:  12
2008:Q3-:Q4
-6.2 -2.5
indice:  13
2008:Q3-:Q4
-8.0 -13.9
indice:  14
2008:Q3-:Q4
-6.8 -1.5
indice:  15
2008:Q3-:Q4
-9.6 -5.5
indice:  16
2008:Q3-:Q4
-7.3 -3.4
indice:  17
2008:Q3-:Q4
-13.2 -8.0
indice:  18
2008:Q3-:Q4
-3.5 -0.9
indice:  19
2008:Q3-:Q4
-2.9 -0.4
indice:  21
2008:Q3-:Q4
-4.3 -19.4
indice:  22
2008:Q3-:Q4
-9.2 -6.1
indice:  23
2008:Q3-:Q4
-5.8 -5.6
indice:  24
2008:Q3-:Q4
-10.7 -3.9
indice:  26
2008:Q3-:Q4
-9.0 -11.6
indice:  28
2008:Q3-:Q4
-5.4 -7.1
indice:  30
2008:Q3-:Q4
-4.6 -9.5
indice:  31
2008:Q3-:Q4
-4.2 -13.8
indice:  33
2008:Q3-:Q4
-8.4 -0.7
indice:  34
2008:Q3-:Q4
-14.9 -22.6
indice:  36
2008:Q3-:Q4
-6.7 -4.4
indice:  37
2008:Q3-:Q4
-4.6 -5.4
indice:  38
2008:Q3-:Q4
-5.5 -2.3
indice:  40
2008:Q3-:Q4
-5.5 -0.5
indice:  42
2008:Q3-:Q4
-13.7 -14.1
indice:  43
2008:Q3-:Q4
-10.6 -1.6
indice:  44
2008:Q3-:Q4
-1.0 -3.0
indice:  45
2008:Q3-:Q4
-0.6 -1.9
indice:  46
2008:Q3-:Q4
-5.9 -5.8
indice:  47
2008:Q3-:Q4
-2.0 -0.9
indice:  48
2008:Q3-:Q4
-2.1 -5.3
indice:  49
2008:Q3-:Q4
-25.2 -27.2
indice:  50
2008:Q3-:Q4
-4.6 -1.0
indice:  52
2008:Q3-:Q4
-6.9 -7.0
indice:  53
2008:Q3-:Q4
-4.0 -4.3
indice:  54
2008:Q3-:Q4
-6.3 -4.4
indice:  55
2008:Q3-:Q4
-12.8 -14.3
indice:  56
2008:Q3-:Q4
-11.4 -6.0
indice:  57
2008:Q3-:Q4
-10.3 -3.1
indice:  58
2008:Q4-2009:Q1
-3.9 -0.2
indice:  0
2008:Q4-2009:Q1
-19.3 -9.2
indice:  1
2008:Q4-2009:Q1
-11.4 -7.2
indice:  2
2008:Q4-2009:Q1
-1.5 -6.0
indice:  4
2008:Q4-2009:Q1
-4.2 -6.8
indice:  5
2008:Q4-2009:Q1
-3.7 -4.1
indice:  9
2008:Q4-2009:Q1
-3.3 -1.1
indice:  11
2008:Q4-2009:Q1
-7.3 -8.7
indice:  12
2008:Q4-2009:Q1
-13.9 -1.8
indice:  14
2008:Q4-2009:Q1
-5.5 -1.0
indice:  16
2008:Q4-2009:Q1
-3.4 -2.4
indice:  17
2008:Q4-2009:Q1
-8.0 -6.9
indice:  18
2008:Q4-2009:Q1
-0.4 -0.4
indice:  21
2008:Q4-2009:Q1
-6.1 -0.6
indice:  23
2008:Q4-2009:Q1
-5.6 -3.4
indice:  24
2008:Q4-2009:Q1
-10.3 -1.2
indice:  25
2008:Q4-2009:Q1
-3.9 -4.4
indice:  26
2008:Q4-2009:Q1
-11.6 -8.1
indice:  28
2008:Q4-2009:Q1
-7.1 -4.3
indice:  30
2008:Q4-2009:Q1
-9.5 -5.8
indice:  31
2008:Q4-2009:Q1
-0.7 -1.5
indice:  34
2008:Q4-2009:Q1
-22.6 -9.9
indice:  36
2008:Q4-2009:Q1
-4.4 -6.7
indice:  37
2008:Q4-2009:Q1
-5.4 -0.7
indice:  38
2008:Q4-2009:Q1
-2.3 -2.4
indice:  40
2008:Q4-2009:Q1
-0.5 -2.0
indice:  42
2008:Q4-2009:Q1
-14.1 -6.8
indice:  43
2008:Q4-2009:Q1
-1.6 -4.6
indice:  44
2008:Q4-2009:Q1
-3.0 -1.4
indice:  45
2008:Q4-2009:Q1
-0.9 -2.7
indice:  48
2008:Q4-2009:Q1
-27.2 -24.3
indice:  50
2008:Q4-2009:Q1
-7.0 -0.5
indice:  53
2008:Q4-2009:Q1
-4.3 -0.5
indice:  54
2008:Q4-2009:Q1
-4.4 -1.5
indice:  55
2008:Q4-2009:Q1
-14.3 -7.1
indice:  56
2008:Q4-2009:Q1
-6.0 -7.8
indice:  57
2008:Q4-2009:Q1
-3.1 -5.2
indice:  58
2009:Q1-:Q2
-9.2 -4.9
indice:  1
2009:Q1-:Q2
-7.2 -2.9
indice:  2
2009:Q1-:Q2
-6.0 -1.2
indice:  4
2009:Q1-:Q2
-4.1 -1.2
indice:  9
2009:Q1-:Q2
-1.1 -2.3
indice:  11
2009:Q1-:Q2
-3.4 -2.5
indice:  24
2009:Q1-:Q2
-8.1 -3.4
indice:  28
2009:Q1-:Q2
-6.7 -0.5
indice:  37
2009:Q1-:Q2
-4.6 -0.2
indice:  44
2009:Q1-:Q2
-24.3 -6.5
indice:  50
2009:Q1-:Q2
-5.2 -1.2
indice:  58
2010:Q2-:Q3
-4.5 -2.5
indice:  32
2010:Q3-:Q4
-2.7 -7.6
indice:  6
2010:Q3-:Q4
-2.2 -1.6
indice:  19
2010:Q3-:Q4
-0.4 -0.7
indice:  24
2010:Q3-:Q4
-0.6 -5.3
indice:  30
2011:Q4-2012:Q1
-6.0 -5.6
indice:  50
2012:Q1-:Q2
-4.4 -2.3
indice:  7
2012:Q1-:Q2
-4.6 -10.1
indice:  16
2012:Q1-:Q2
-5.6 -9.8
indice:  50
2012:Q2-:Q3
-2.4 -4.2
indice:  1
2012:Q2-:Q3
-2.3 -6.6
indice:  7
2012:Q2-:Q3
-6.1 -3.6
indice:  18
2012:Q2-:Q3
-1.9 -4.9
indice:  19
2012:Q2-:Q3
-1.0 -4.4
indice:  24
2012:Q2-:Q3
-4.7 -3.1
indice:  31
2012:Q2-:Q3
-2.8 -5.9
indice:  45
2012:Q2-:Q3
-4.6 -2.9
indice:  48
2012:Q2-:Q3
-9.8 -0.1
indice:  50
2012:Q3-:Q4
-6.6 -4.3
indice:  7
2012:Q3-:Q4
-3.6 -0.7
indice:  18
2012:Q4-2013:Q1
-3.6 -1.0
indice:  6
2012:Q4-2013:Q1
-0.7 -5.0
indice:  18
2013:Q1-:Q2
-1.1 -1.6
indice:  45
2013:Q3-:Q4
-1.1 -4.2
indice:  0
2013:Q3-:Q4
-3.4 -0.2
indice:  24
2014:Q2-:Q3
-4.2 -12.0
indice:  1
2014:Q2-:Q3
-5.2 -3.0
indice:  41
2014:Q3-:Q4
-12.0 -19.0
indice:  1
2014:Q3-:Q4
-1.3 -2.8
indice:  14
2014:Q3-:Q4
-0.3 -10.7
indice:  18
2014:Q3-:Q4
-7.0 -17.2
indice:  36
2014:Q3-:Q4
-3.1 -3.2
indice:  43
2014:Q3-:Q4
-2.7 -9.4
indice:  48
2014:Q3-:Q4
-4.9 -13.0
indice:  50
2014:Q3-:Q4
-2.7 -3.6
indice:  56
2014:Q4-2015:Q1
-10.7 -1.2
indice:  18
2014:Q4-2015:Q1
-22.4 -6.9
indice:  34
2014:Q4-2015:Q1
-17.2 -4.8
indice:  36
2014:Q4-2015:Q1
-3.2 -1.4
indice:  43
2014:Q4-2015:Q1
-13.0 -1.8
indice:  50
2014:Q4-2015:Q1
-3.6 -0.8
indice:  56
2015:Q1-:Q2
-1.2 -3.0
indice:  18
2015:Q1-:Q2
-6.9 -6.7
indice:  34
2015:Q1-:Q2
-1.8 -1.4
indice:  50
2015:Q2-:Q3
-7.5 -5.6
indice:  1
2015:Q2-:Q3
-10.7 -3.1
indice:  7
2015:Q2-:Q3
-3.0 -7.7
indice:  18
2015:Q2-:Q3
-0.3 -9.0
indice:  26
2015:Q2-:Q3
-2.6 -4.0
indice:  31
2015:Q2-:Q3
-6.7 -6.7
indice:  34
2015:Q2-:Q3
-3.1 -3.5
indice:  48
2015:Q2-:Q3
-1.4 -10.7
indice:  50
2015:Q3-:Q4
-5.6 -4.5
indice:  1
2015:Q3-:Q4
-0.5 -1.7
indice:  3
2015:Q3-:Q4
-3.1 -9.6
indice:  7
2015:Q3-:Q4
-1.3 -1.7
indice:  13
2015:Q3-:Q4
-0.2 -2.3
indice:  15
2015:Q3-:Q4
-7.7 -9.2
indice:  18
2015:Q3-:Q4
-9.0 -7.3
indice:  26
2015:Q3-:Q4
-1.2 -3.3
indice:  27
2015:Q3-:Q4
-4.0 -2.9
indice:  31
2015:Q3-:Q4
-6.7 -18.4
indice:  34
2015:Q3-:Q4
-4.3 -13.4
indice:  36
2015:Q3-:Q4
-1.4 -5.4
indice:  43
2015:Q3-:Q4
-3.5 -5.3
indice:  48
2015:Q3-:Q4
-10.7 -13.8
indice:  50
2015:Q3-:Q4
-0.8 -4.8
indice:  56
2015:Q4-2016:Q1
-2.3 -1.1
indice:  15
2015:Q4-2016:Q1
-7.3 -1.2
indice:  26
2015:Q4-2016:Q1
-18.4 -2.9
indice:  34
2015:Q4-2016:Q1
-13.8 -2.2
indice:  50
2016:Q1-:Q2
-2.2 -2.5
indice:  50
2016:Q3-:Q4
-1.5 -4.1
indice:  39
2016:Q4-2017:Q1
-2.7 -9.2
indice:  7
2017:Q1-:Q2
-0.8 -0.4
indice:  23
2017:Q1-:Q2
-3.8 -3.9
indice:  41
2017:Q2-:Q3
-3.9 -2.6
indice:  41
2018:Q3-:Q4
-3.8 -4.1
indice:  34
2018:Q3-:Q4
-0.4 -8.7
indice:  48
2018:Q4-2019:Q1
-1.4 -2.1
indice:  18
2019:Q1-:Q2
-2.1 -1.2
indice:  18
2019:Q2-:Q3
-1.2 -3.6
indice:  18
2019:Q3-:Q4
-1.0 -12.1
indice:  1
2019:Q3-:Q4
-0.9 -5.9
indice:  13
2019:Q3-:Q4
-3.6 -15.6
indice:  18
2019:Q3-:Q4
-2.3 -12.9
indice:  36
2019:Q4-2020:Q1
-12.1 -40.8
indice:  1
2019:Q4-2020:Q1
-4.3 -30.0
indice:  4
2019:Q4-2020:Q1
-9.4 -31.5
indice:  6
2019:Q4-2020:Q1
-6.0 -23.5
indice:  7
2019:Q4-2020:Q1
-5.4 -28.8
indice:  10
2019:Q4-2020:Q1
-13.9 -44.2
indice:  11
2019:Q4-2020:Q1
-5.9 -30.9
indice:  13
2019:Q4-2020:Q1
-2.3 -34.8
indice:  14
2019:Q4-2020:Q1
-4.0 -29.9
indice:  15
2019:Q4-2020:Q1
-1.9 -34.5
indice:  17
2019:Q4-2020:Q1
-15.6 -35.2
indice:  18
2019:Q4-2020:Q1
-7.3 -24.2
indice:  20
2019:Q4-2020:Q1
-3.3 -39.8
indice:  22
2019:Q4-2020:Q1
-4.2 -29.6
indice:  23
2019:Q4-2020:Q1
-1.7 -28.1
indice:  25
2019:Q4-2020:Q1
-2.6 -25.6
indice:  26
2019:Q4-2020:Q1
-0.9 -24.9
indice:  27
2019:Q4-2020:Q1
-4.0 -51.2
indice:  28
2019:Q4-2020:Q1
-1.8 -36.0
indice:  30
2019:Q4-2020:Q1
-3.8 -37.5
indice:  31
2019:Q4-2020:Q1
-1.1 -33.0
indice:  32
2019:Q4-2020:Q1
-10.8 -41.8
indice:  34
2019:Q4-2020:Q1
-4.3 -32.8
indice:  35
2019:Q4-2020:Q1
-12.9 -35.3
indice:  36
2019:Q4-2020:Q1
-4.6 -36.8
indice:  38
2019:Q4-2020:Q1
-0.7 -32.9
indice:  39
2019:Q4-2020:Q1
-7.9 -24.6
indice:  40
2019:Q4-2020:Q1
-9.6 -32.5
indice:  43
2019:Q4-2020:Q1
-1.0 -25.5
indice:  46
2019:Q4-2020:Q1
-3.8 -39.4
indice:  48
2019:Q4-2020:Q1
-5.1 -28.8
indice:  49
2019:Q4-2020:Q1
-13.1 -45.5
indice:  50
2019:Q4-2020:Q1
-0.6 -31.2
indice:  51
2019:Q4-2020:Q1
-2.6 -32.8
indice:  52
2019:Q4-2020:Q1
-4.4 -33.4
indice:  53
2019:Q4-2020:Q1
-1.3 -29.3
indice:  54
2019:Q4-2020:Q1
-1.5 -29.7
indice:  55
2019:Q4-2020:Q1
-8.2 -31.3
indice:  56
2019:Q4-2020:Q1
-0.1 -27.8
indice:  57
2019:Q4-2020:Q1
-3.2 -30.3
indice:  58

En la base de datos que obtuve por medio de la Api tenemos información demás para nuestro estudio, (hay varios estados que no los tenemos en las bases que ya nos dieron), procedemos a elimimnar estos registros.

In [15]:
PIBxEstados=PIB

In [16]:
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Southeast"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Southwest"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Mideast"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Far West"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Plains"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Rocky Mountain"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="Great Lakes"].index)
PIBxEstados = PIBxEstados.drop(PIBxEstados[PIBxEstados['GeoName']=="New England"].index)

Antes mencionamos que debíamos tomar una desición sobre a partir de qué fecha y hasta qué fecha vamos a hacer  nuestro estudio,
por concenso de  nuestro grupo, decidimos hacerlo en el siguiente rango de fecha: 2010-2020, ya que la información más completa que tenemos está en este rango.
Por esta razón procedo a eliminar de la base de datos de PIB las columnas que por ahora no necesitamos.

In [17]:
PIBxEstados.drop(["GeoFips","2005:Q1-:Q2","2005:Q2-:Q3","2005:Q3-:Q4","2005:Q4-2006:Q1","2006:Q1-:Q2","2006:Q2-:Q3",
                 "2006:Q3-:Q4","2006:Q4-2007:Q1","2007:Q1-:Q2","2007:Q2-:Q3","2007:Q3-:Q4","2007:Q4-2008:Q1","2008:Q1-:Q2",
                 "2008:Q2-:Q3","2008:Q3-:Q4","2008:Q4-2009:Q1","2009:Q1-:Q2","2009:Q2-:Q3","2009:Q3-:Q4",
                 "2020:Q1-:Q2","2020:Q2-:Q3","2020:Q3-:Q4","2020:Q4-2021:Q1","2021:Q1-:Q2","2021:Q2-:Q3","2021:Q3-:Q4",
                 "2021:Q4-2022:Q1","2022:Q1-:Q2"],axis=1,inplace=True)

personalmente me gusta hacer copias de las bases por si tengo algún error y así no cargar desde el comienzo estas bases:

In [18]:
df1=PIBxEstados.copy()
df2=data.copy()

Para comprender mejor la información que tengo de la base de datos que obtuve de la API,sobre el PIB, hago el cambio de nombre de las columnas correspondintes(cada registro tendra la información de la variación del PIB con respecto al período pasado)

In [19]:
df1.rename(columns={'2009:Q4-2010:Q1':'trim1_2010','2010:Q1-:Q2':'trim2_2010','2010:Q2-:Q3':'trim3_2010','2010:Q3-:Q4':'trim4_2010',
          '2010:Q4-2011:Q1':'trim1_2011','2011:Q1-:Q2':'trim2_2011','2011:Q2-:Q3':'trim3_2011','2011:Q3-:Q4':'trim4_2011',
          '2011:Q4-2012:Q1':'trim1_2012','2012:Q1-:Q2':'trim2_2012','2012:Q2-:Q3':'trim3_2012','2012:Q3-:Q4':'trim4_2012',
          '2012:Q4-2013:Q1':'trim1_2013','2013:Q1-:Q2':'trim2_2013','2013:Q2-:Q3':'trim3_2013','2013:Q3-:Q4':'trim4_2013',
          '2013:Q4-2014:Q1':'trim1_2014','2014:Q1-:Q2':'trim2_2014','2014:Q2-:Q3':'trim3_2014','2014:Q3-:Q4':'trim4_2014',
          '2014:Q4-2015:Q1':'trim1_2015','2015:Q1-:Q2':'trim2_2015','2015:Q2-:Q3':'trim3_2015','2015:Q3-:Q4':'trim4_2015',
          '2015:Q4-2016:Q1':'trim1_2016','2016:Q1-:Q2':'trim2_2016','2016:Q2-:Q3':'trim3_2016','2016:Q3-:Q4':'trim4_2016',
          '2016:Q4-2017:Q1':'trim1_2017','2017:Q1-:Q2':'trim2_2017','2017:Q2-:Q3':'trim3_2017','2017:Q3-:Q4':'trim4_2017',
          '2017:Q4-2018:Q1':'trim1_2018','2018:Q1-:Q2':'trim2_2018','2018:Q2-:Q3':'trim3_2018','2018:Q3-:Q4':'trim4_2018',
          '2018:Q4-2019:Q1':'trim1_2019','2019:Q1-:Q2':'trim2_2019','2019:Q2-:Q3':'trim3_2019','2019:Q3-:Q4':'trim4_2019',
          '2019:Q4-2020:Q1':'trim1_2020'},inplace=True )

a continuación cambio el nombre de la columna "GeoName"

In [20]:
df1.rename({'GeoName': 'region'}, axis=1,inplace=True)

A continuación creo un dataframe de cada trimestre por año, es la alternativa que tuve para así luego cargarlo a la base de datos general y poder así ir insertando según el período correspondiente. Tal vez con seguridad se pueda optimizar este proceso, pero por ahora es mi solución para el problema planteado.

In [21]:
T1_2010=df1.groupby("region")[["trim1_2010"]].sum()
T1_2010 = T1_2010.reset_index()
T2_2010=df1.groupby("region")[["trim2_2010"]].sum()
T2_2010 = T2_2010.reset_index()
T3_2010=df1.groupby("region")[["trim3_2010"]].sum()
T3_2010 = T3_2010.reset_index()
T4_2010=df1.groupby("region")[["trim4_2010"]].sum()
T4_2010 = T4_2010.reset_index()

In [22]:
T1_2011=df1.groupby("region")[["trim1_2011"]].sum()
T1_2011 = T1_2011.reset_index()
T2_2011=df1.groupby("region")[["trim2_2011"]].sum()
T2_2011 = T2_2011.reset_index()
T3_2011=df1.groupby("region")[["trim3_2011"]].sum()
T3_2011 = T3_2011.reset_index()       
T4_2011=df1.groupby("region")[["trim4_2011"]].sum()
T4_2011 = T4_2011.reset_index()

In [23]:
T1_2012=df1.groupby("region")[["trim1_2012"]].sum()
T1_2012 = T1_2012.reset_index()
T2_2012=df1.groupby("region")[["trim2_2012"]].sum()
T2_2012 = T2_2012.reset_index()
T3_2012=df1.groupby("region")[["trim3_2012"]].sum()
T3_2012 = T3_2012.reset_index()
T4_2012=df1.groupby("region")[["trim4_2012"]].sum()
T4_2012 = T4_2012.reset_index()

In [24]:
T1_2013=df1.groupby("region")[["trim1_2013"]].sum()
T1_2013 = T1_2013.reset_index()
T2_2013=df1.groupby("region")[["trim2_2013"]].sum()
T2_2013 = T2_2013.reset_index()
T3_2013=df1.groupby("region")[["trim3_2013"]].sum()
T3_2013 = T3_2013.reset_index()
T4_2013=df1.groupby("region")[["trim4_2013"]].sum()
T4_2013 = T4_2013.reset_index()

In [25]:
T1_2014=df1.groupby("region")[["trim1_2014"]].sum()
T1_2014 = T1_2014.reset_index()
T2_2014=df1.groupby("region")[["trim2_2014"]].sum()
T2_2014 = T2_2014.reset_index()
T3_2014=df1.groupby("region")[["trim3_2014"]].sum()
T3_2014 = T3_2014.reset_index()
T4_2014=df1.groupby("region")[["trim4_2014"]].sum()
T4_2014 = T4_2014.reset_index()

In [26]:
T1_2015=df1.groupby("region")[["trim1_2015"]].sum()
T1_2015 = T1_2015.reset_index()
T2_2015=df1.groupby("region")[["trim2_2015"]].sum()
T2_2015 = T2_2015.reset_index()
T3_2015=df1.groupby("region")[["trim3_2015"]].sum()
T3_2015 = T3_2015.reset_index()
T4_2015=df1.groupby("region")[["trim4_2015"]].sum()
T4_2015 = T4_2015.reset_index()

In [27]:
T1_2016=df1.groupby("region")[["trim1_2016"]].sum()
T1_2016 = T1_2016.reset_index()
T2_2016=df1.groupby("region")[["trim2_2016"]].sum()
T2_2016 = T2_2016.reset_index()
T3_2016=df1.groupby("region")[["trim3_2016"]].sum()
T3_2016 = T3_2016.reset_index()
T4_2016=df1.groupby("region")[["trim4_2016"]].sum()
T4_2016 = T4_2016.reset_index()

In [28]:
T1_2017=df1.groupby("region")[["trim1_2017"]].sum()
T1_2017 = T1_2017.reset_index()
T2_2017=df1.groupby("region")[["trim2_2017"]].sum()
T2_2017 = T2_2017.reset_index()
T3_2017=df1.groupby("region")[["trim3_2017"]].sum()
T3_2017 = T3_2017.reset_index()
T4_2017=df1.groupby("region")[["trim4_2017"]].sum()
T4_2017 = T4_2017.reset_index()

In [29]:
T1_2018=df1.groupby("region")[["trim1_2018"]].sum()
T1_2018 = T1_2018.reset_index()
T2_2018=df1.groupby("region")[["trim2_2018"]].sum()
T2_2018 = T2_2018.reset_index()
T3_2018=df1.groupby("region")[["trim3_2018"]].sum()
T3_2018 = T3_2018.reset_index()
T4_2018=df1.groupby("region")[["trim4_2018"]].sum()
T4_2018 = T4_2018.reset_index()

In [30]:
T1_2019=df1.groupby("region")[["trim1_2019"]].sum()
T1_2019 = T1_2019.reset_index()
T2_2019=df1.groupby("region")[["trim2_2019"]].sum()
T2_2019 = T2_2019.reset_index()
T3_2019=df1.groupby("region")[["trim3_2019"]].sum()
T3_2019 = T3_2019.reset_index()
T4_2019=df1.groupby("region")[["trim4_2019"]].sum()
T4_2019 = T4_2019.reset_index()

In [31]:
T1_2020=df1.groupby("region")[["trim1_2020"]].sum()
T1_2020 = T1_2020.reset_index()

Debido a que debo insertar los valores a la base de datos general del PIB, debo asegurarme que los períodos coincidan, por esta razón de la columna date (fecha) de la tabla general, hago un split para separar en dos columnas diferentes el año y el numero del mes, luego de esto hago un for y creo otra columna donde me da el valor del trimestre correspondiente a cada año en cuestión. Para asi poder insertar los valores correspondientes del PIB.

In [32]:
listaEstados=list(T1_2010["region"])

In [33]:
listadf2=list(df2["region"].unique())

creo una columna "valorPIB" con valor de cero a cada registro por ahora para posteriormente insertar sus valores correspondientes

In [34]:
df2=df2.assign(valorPIB=0)

In [35]:
df3=df2["date"].str.split('-',expand=True)

In [36]:
new_df=df3

In [37]:
for i in range(38913):
    if new_df[1][i]=='01':
        new_df[1][i]='1'
    if new_df[1][i]=='02':
        new_df[1][i]='1'
    if new_df[1][i]=='03':
        new_df[1][i]='1'
    if new_df[1][i]=='04':
        new_df[1][i]='2'
    if new_df[1][i]=='05':
        new_df[1][i]='2'
    if new_df[1][i]=='06':
        new_df[1][i]='2'
    if new_df[1][i]=='07':
        new_df[1][i]='3'
    if new_df[1][i]=='08':
        new_df[1][i]='3' 
    if new_df[1][i]=='09':
        new_df[1][i]='3'
    if new_df[1][i]=='10':
        new_df[1][i]='4'
    if new_df[1][i]=='11':
        new_df[1][i]='4'
    if new_df[1][i]=='12':
        new_df[1][i]='4'

A continuacion uno este datframe al general y poder tener solo una tabla con toda la información que necesito

In [38]:
df2 = pd.concat([df2, new_df], axis=1)

renombro las columnas correspondientes

In [39]:
df2.rename({0:'año',1:'trimestre'},axis=1,inplace=True)

la columna "valorPIB" es de tipo entero, así que procedo a cambiarle el tipo a float.

In [40]:
df2["valorPIB"]=df2["valorPIB"].astype(float)

Ya con los datos hasta aquí hago un for para cada trimestre de cada año (algo tedioso, pero por ahora es mi alternativa, pero muy seguro de que la información esté bien insertada), se van insertando en la tabla hasta llenarla completamente

In [41]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2010[T1_2010["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2010':
                  df2["valorPIB"][n]=T1_2010["trim1_2010"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1859985564.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2010["trim1_2010"][ind[0]]

In [42]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2010[T2_2010["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2010':
                  df2["valorPIB"][n]=T2_2010["trim2_2010"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2648697189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2010["trim2_2010"][ind[0]]

In [43]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2010[T3_2010["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2010':
                  df2["valorPIB"][n]=T3_2010["trim3_2010"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1123262335.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2010["trim3_2010"][ind[0]]

In [44]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2010[T4_2010["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2010':
                  df2["valorPIB"][n]=T4_2010["trim4_2010"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\671869068.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2010["trim4_2010"][ind[0]]

In [45]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2011[T1_2011["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2011':
                  df2["valorPIB"][n]=T1_2011["trim1_2011"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2897545489.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2011["trim1_2011"][ind[0]]

In [46]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2011[T2_2011["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2011':
                  df2["valorPIB"][n]=T2_2011["trim2_2011"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2216798127.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2011["trim2_2011"][ind[0]]

In [47]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2011[T3_2011["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2011':
                  df2["valorPIB"][n]=T3_2011["trim3_2011"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2627848058.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2011["trim3_2011"][ind[0]]

In [48]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2011[T4_2011["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2011':
                  df2["valorPIB"][n]=T4_2011["trim4_2011"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2733717936.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2011["trim4_2011"][ind[0]]

In [49]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2012[T1_2012["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2012':
                  df2["valorPIB"][n]=T1_2012["trim1_2012"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\616316723.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2012["trim1_2012"][ind[0]]

In [50]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2012[T2_2012["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2012':
                  df2["valorPIB"][n]=T2_2012["trim2_2012"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3205022706.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2012["trim2_2012"][ind[0]]

In [51]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2012[T3_2012["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2012':
                  df2["valorPIB"][n]=T3_2012["trim3_2012"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3522233222.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2012["trim3_2012"][ind[0]]

In [52]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2012[T4_2012["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2012':
                  df2["valorPIB"][n]=T4_2012["trim4_2012"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\661772720.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2012["trim4_2012"][ind[0]]

In [53]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2013[T1_2013["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2013':
                  df2["valorPIB"][n]=T1_2013["trim1_2013"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3537607301.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2013["trim1_2013"][ind[0]]

In [54]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2013[T2_2013["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2013':
                  df2["valorPIB"][n]=T2_2013["trim2_2013"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\188401253.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2013["trim2_2013"][ind[0]]

In [55]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2013[T3_2013["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2013':
                  df2["valorPIB"][n]=T3_2013["trim3_2013"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\4011107379.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2013["trim3_2013"][ind[0]]

In [56]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2013[T4_2013["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2013':
                  df2["valorPIB"][n]=T4_2013["trim4_2013"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\4083472926.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2013["trim4_2013"][ind[0]]

In [57]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2014[T1_2014["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2014':
                  df2["valorPIB"][n]=T1_2014["trim1_2014"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1408930638.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2014["trim1_2014"][ind[0]]

In [58]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2014[T2_2014["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2014':
                  df2["valorPIB"][n]=T2_2014["trim2_2014"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2765995159.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2014["trim2_2014"][ind[0]]

In [59]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2014[T3_2014["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2014':
                  df2["valorPIB"][n]=T3_2014["trim3_2014"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1962829835.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2014["trim3_2014"][ind[0]]

In [60]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2014[T4_2014["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2014':
                  df2["valorPIB"][n]=T4_2014["trim4_2014"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\90320560.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2014["trim4_2014"][ind[0]]

In [61]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2015[T1_2015["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2015':
                  df2["valorPIB"][n]=T1_2015["trim1_2015"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1078907362.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2015["trim1_2015"][ind[0]]

In [62]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2015[T2_2015["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2015':
                  df2["valorPIB"][n]=T2_2015["trim2_2015"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3010285180.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2015["trim2_2015"][ind[0]]

In [63]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2015[T3_2015["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2015':
                  df2["valorPIB"][n]=T3_2015["trim3_2015"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3672660494.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2015["trim3_2015"][ind[0]]

In [64]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2015[T4_2015["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2015':
                  df2["valorPIB"][n]=T4_2015["trim4_2015"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2236459115.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2015["trim4_2015"][ind[0]]

In [65]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2016[T1_2016["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2016':
                  df2["valorPIB"][n]=T1_2016["trim1_2016"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1198528695.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2016["trim1_2016"][ind[0]]

In [66]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2016[T2_2016["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2016':
                  df2["valorPIB"][n]=T2_2016["trim2_2016"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2601655770.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2016["trim2_2016"][ind[0]]

In [67]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2016[T3_2016["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2016':
                  df2["valorPIB"][n]=T3_2016["trim3_2016"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3123404792.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2016["trim3_2016"][ind[0]]

In [68]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2016[T4_2016["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2016':
                  df2["valorPIB"][n]=T4_2016["trim4_2016"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\1851093109.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2016["trim4_2016"][ind[0]]

In [69]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2017[T1_2017["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2017':
                  df2["valorPIB"][n]=T1_2017["trim1_2017"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2134917458.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2017["trim1_2017"][ind[0]]

In [70]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2017[T2_2017["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2017':
                  df2["valorPIB"][n]=T2_2017["trim2_2017"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\125029859.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2017["trim2_2017"][ind[0]]

In [71]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2017[T3_2017["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2017':
                  df2["valorPIB"][n]=T3_2017["trim3_2017"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\701085042.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2017["trim3_2017"][ind[0]]

In [72]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2017[T4_2017["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2017':
                  df2["valorPIB"][n]=T4_2017["trim4_2017"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2219016787.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2017["trim4_2017"][ind[0]]

In [73]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2018[T1_2018["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2018':
                  df2["valorPIB"][n]=T1_2018["trim1_2018"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2433199940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2018["trim1_2018"][ind[0]]

In [74]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2018[T2_2018["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2018':
                  df2["valorPIB"][n]=T2_2018["trim2_2018"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3069557818.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2018["trim2_2018"][ind[0]]

In [75]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2018[T3_2018["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2018':
                  df2["valorPIB"][n]=T3_2018["trim3_2018"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\665222656.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2018["trim3_2018"][ind[0]]

In [76]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2018[T4_2018["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2018':
                  df2["valorPIB"][n]=T4_2018["trim4_2018"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3918106225.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2018["trim4_2018"][ind[0]]

In [77]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2019[T1_2019["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2019':
                  df2["valorPIB"][n]=T1_2019["trim1_2019"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2292956720.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T1_2019["trim1_2019"][ind[0]]

In [78]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T2_2019[T2_2019["region"]==i].index
                if df2["trimestre"][n]=="2" and df2["año"][n]=='2019':
                  df2["valorPIB"][n]=T2_2019["trim2_2019"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\3799350984.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T2_2019["trim2_2019"][ind[0]]

In [79]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T3_2019[T3_2019["region"]==i].index
                if df2["trimestre"][n]=="3" and df2["año"][n]=='2019':
                  df2["valorPIB"][n]=T3_2019["trim3_2019"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\2864540346.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T3_2019["trim3_2019"][ind[0]]

In [80]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T4_2019[T4_2019["region"]==i].index
                if df2["trimestre"][n]=="4" and df2["año"][n]=='2019':
                  df2["valorPIB"][n]=T4_2019["trim4_2019"][ind[0]]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2428\624380616.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valorPIB"][n]=T4_2019["trim4_2019"][ind[0]]

In [81]:
for i in listadf2:
    for j in listaEstados:
        if i==j:
            listaind=df2[df2["region"]==i].index
            for n in listaind:
                ind=T1_2020[T1_2020["region"]==i].index
                if df2["trimestre"][n]=="1" and df2["año"][n]=='2020':
                  df2["valorPIB"][n]=T1_2020["trim1_2020"][ind[0]]

In [ ]:
#pd.DataFrame(df2).to_csv('csvPIB.csv',index=False)

luego de que ya tengo en la tabla general toda la información requerida, busco mostrar de una forma mejor entendible la información del PIB, haciendo una evaluación de este, tomando información de la web y escuchando opiniones de economistas, hacemos la siguiente valoración:
PIB<0 quiere decir que la economia en esa zona está decreciendo
PIB entre 0 y 2 la economía en esta zona es estable
PIB>0 la economía en esta zona está en aumento

In [82]:
df4=df2.copy()

In [83]:
condiciones=[
    (df4["valorPIB"]>2),
    (df4["valorPIB"]>=0) & (df4["valorPIB"]<=2),
    (df4["valorPIB"]<0)
]
opciones=["CRECIMIENTO_INERCIAL","ESTABLE","DECRECIMIENTO"]
df4["resumenPIB"]=np.select(condiciones,opciones)

In [84]:
df4.head(50)

,region,date,price,rent,property_type,roi,valorPIB,año,trimestre,resumenPIB
0,California,2010-02,231512.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL
1,California,2010-03,230640.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL
2,California,2010-04,230508.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL
3,California,2010-05,230649.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL
4,California,2010-06,229228.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL
5,California,2010-07,227264.0,NaN,1Bedroom,NaN,3.2,2010,3,CRECIMIENTO_INERCIAL
6,California,2010-08,225162.0,NaN,1Bedroom,NaN,3.2,2010,3,CRECIMIENTO_INERCIAL
7,California,2010-09,223295.0,NaN,1Bedroom,NaN,3.2,2010,3,CRECIMIENTO_INERCIAL
8,California,2010-10,221244.0,1195.0,1Bedroom,185.141423,11.3,2010,4,CRECIMIENTO_INERCIAL
9,California,2010-11,218563.0,1200.0,1Bedroom,182.135833,11.3,2010,4,CRECIMIENTO_INERCIAL
10,California,2010-12,216192.0,1215.5,1Bedroom,177.862608,11.3,2010,4,CRECIMIENTO_INERCIAL
11,California,2011-01,214229.0,1195.0,1Bedroom,179.271130,0.3,2011,1,ESTABLE
12,California,2011-02,212749.0,1200.0,1Bedroom,177.290833,0.3,2011,1,ESTABLE
13,California,2011-03,210900.0,1200.0,1Bedroom,175.750000,0.3,2011,1,ESTABLE
14,California,2011-04,208812.0,1200.0,1Bedroom,174.010000,2.9,2011,2,CRECIMIENTO_INERCIAL
15,California,2011-05,206043.0,1215.0,1Bedroom,169.582716,2.9,2011,2,CRECIMIENTO_INERCIAL
16,California,2011-06,204318.0,1200.0,1Bedroom,170.265000,2.9,2011,2,CRECIMIENTO_INERCIAL
17,California,2011-07,202940.0,1222.5,1Bedroom,166.004090,1.0,2011,3,ESTABLE
18,California,2011-08,201518.0,1250.0,1Bedroom,161.214400,1.0,2011,3,ESTABLE
19,California,2011-09,199927.0,1250.0,1Bedroom,159.941600,1.0,2011,3,ESTABLE
20,California,2011-10,198290.0,1195.0,1Bedroom,165.933054,2.0,2011,4,ESTABLE
21,California,2011-11,197676.0,1150.0,1Bedroom,171.892174,2.0,2011,4,ESTABLE
22,California,2011-12,196752.0,1150.0,1Bedroom,171.088696,2.0,2011,4,ESTABLE
23,California,2012-01,196095.0,1195.0,1Bedroom,164.096234,8.6,2012,1,CRECIMIENTO_INERCIAL
24,California,2012-02,195513.0,1200.0,1Bedroom,162.927500,8.6,2012,1,CRECIMIENTO_INERCIAL
25,California,2012-03,195422.0,1265.0,1Bedroom,154.483794,8.6,2012,1,CRECIMIENTO_INERCIAL
26,California,2012-04,195808.0,1250.0,1Bedroom,156.646400,2.9,2012,2,CRECIMIENTO_INERCIAL
27,California,2012-05,196972.0,1245.0,1Bedroom,158.210442,2.9,2012,2,CRECIMIENTO_INERCIAL
28,California,2012-06,198462.0,1250.0,1Bedroom,158.769600,2.9,2012,2,CRECIMIENTO_INERCIAL
29,California,2012-07,200195.0,1250.0,1Bedroom,160.156000,4.5,2012,3,CRECIMIENTO_INERCIAL
30,California,2012-08,202267.0,1290.0,1Bedroom,156.796124,4.5,2012,3,CRECIMIENTO_INERCIAL
31,California,2012-09,204645.0,1315.0,1Bedroom,155.623574,4.5,2012,3,CRECIMIENTO_INERCIAL
32,California,2012-10,207728.0,1310.0,1Bedroom,158.570992,8.1,2012,4,CRECIMIENTO_INERCIAL
33,California,2012-11,210711.0,1325.0,1Bedroom,159.027170,8.1,2012,4,CRECIMIENTO_INERCIAL
34,California,2012-12,214514.0,1299.0,1Bedroom,165.137798,8.1,2012,4,CRECIMIENTO_INERCIAL
35,California,2013-01,218525.0,1270.0,1Bedroom,172.066929,1.5,2013,1,ESTABLE
36,California,2013-02,222985.0,1299.0,1Bedroom,171.658968,1.5,2013,1,ESTABLE
37,California,2013-03,228103.0,1330.0,1Bedroom,171.506015,1.5,2013,1,ESTABLE
38,California,2013-04,233753.0,1298.0,1Bedroom,180.087057,4.5,2013,2,CRECIMIENTO_INERCIAL
39,California,2013-05,239646.0,1295.0,1Bedroom,185.054826,4.5,2013,2,CRECIMIENTO_INERCIAL
40,California,2013-06,245550.0,1255.0,1Bedroom,195.657371,4.5,2013,2,CRECIMIENTO_INERCIAL
41,California,2013-07,251245.0,1250.0,1Bedroom,200.996000,6.9,2013,3,CRECIMIENTO_INERCIAL
42,California,2013-08,257136.0,1250.0,1Bedroom,205.708800,6.9,2013,3,CRECIMIENTO_INERCIAL
43,California,2013-09,262337.0,1300.0,1Bedroom,201.797692,6.9,2013,3,CRECIMIENTO_INERCIAL
44,California,2013-10,266748.0,1345.0,1Bedroom,198.325651,12.1,2013,4,CRECIMIENTO_INERCIAL
45,California,2013-11,270527.0,1250.0,1Bedroom,216.421600,12.1,2013,4,CRECIMIENTO_INERCIAL
46,California,2013-12,273867.0,1392.5,1Bedroom,196.672890,12.1,2013,4,CRECIMIENTO_INERCIAL
47,California,2014-01,277177.0,1400.0,1Bedroom,197.983571,-2.7,2014,1,DECRECIMIENTO
48,California,2014-02,280132.0,1345.0,1Bedroom,208.276580,-2.7,2014,1,DECRECIMIENTO
49,California,2014-03,281918.0,1320.0,1Bedroom,213.574242,-2.7,2014,1,DECRECIMIENTO

In [85]:
final=df4.copy()

Por último, para poder relacionar esta tabla con una base de datos de todo el proyecto, agregamos una columna adicional que nos servirá, como primary key para la correspontiente relación; tomamos de la columna de los Estados y la abreviamos.

In [86]:
#Primero creamos la columna y la rellenamos con los mismos valores de la columna estado
final['Id_estado'] = final['region']
#luego aplicamos la conversion de la columna creada
final['Id_estado'] = final['Id_estado'].map({'California':'CA','Texas':'TX','New York':'NY','Florida':'FL',
'Illinois':'IL','Pennsylvania':'PA','Ohio':'OH','Michigan':'MI','Georgia':'GA','North Carolina':'NC','New Jersey':'NJ',
'Virginia':'VA','Washington':'WA','Massachusetts':'MA','Indiana':'IN','Arizona':'AZ','Tennessee':'TN','Missouri':'MO',
'Maryland':'MD','Wisconsin':'WI','Minnesota':'MN','Colorado':'CO','Alabama':'AL','South Carolina':'SC','Louisiana':'LA',
'Kentucky':'KY','Oregon':'OR','Oklahoma':'OK','Connecticut':'CT','Iowa':'IA','Mississippi':'MS','Arkansas':'AR','Kansas':'KS',
'Utah':'UT','Nevada':'NV','New Mexico':'NM','West Virginia':'WV','Nebraska':'NE','Idaho':'ID','Hawaii':'HI','Maine':'ME',
'New Hampshire':'NH','Rhode Island':'RI','Montana':'MT','Delaware':'DE','South Dakota':'SD','Alaska':'AK','North Dakota':'ND',
'Vermont':'VT','Wyoming':'WT'}, na_action =None)

In [87]:
final

,region,date,price,rent,property_type,roi,valorPIB,año,trimestre,resumenPIB,Id_estado
0,California,2010-02,231512.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL,CA
1,California,2010-03,230640.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL,CA
2,California,2010-04,230508.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
3,California,2010-05,230649.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
4,California,2010-06,229228.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
...,...,...,...,...,...,...,...,...,...,...,...
38908,Wyoming,2019-08,248786.0,1275.0,Sfr,195.126275,5.0,2019,3,CRECIMIENTO_INERCIAL,WT
38909,Wyoming,2019-09,250004.0,1250.0,Sfr,200.003200,5.0,2019,3,CRECIMIENTO_INERCIAL,WT
38910,Wyoming,2019-10,251161.0,1197.5,Sfr,209.737787,6.1,2019,4,CRECIMIENTO_INERCIAL,WT
38911,Wyoming,2019-11,252114.0,1200.0,Sfr,210.095000,6.1,2019,4,CRECIMIENTO_INERCIAL,WT
38912,Wyoming,2019-12,253160.0,1150.0,Sfr,220.139130,6.1,2019,4,CRECIMIENTO_INERCIAL,WT

para comprender mejor los nombre de las columnas, los renombramos:

In [95]:
final.rename(columns={'date':'fecha','price':'precio','rent':'valor_alquiler','property_type':'tipo_propiedad'},inplace=True)

In [96]:
final.head(1)

,region,fecha,precio,valor_alquiler,tipo_propiedad,roi,valorPIB,año,trimestre,resumenPIB,Id_estado
0,California,2010-02,231512.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL,CA

In [97]:
sinDColumbia=final.copy()

Según nuestros análisis el Estado de "District of Columbia" no debemos tenerlo en cuenta en estos estudios, debido a que es un Estado especial, y debido a esto los valores son totalmente diferentes a los demás estados, seria para n osotros como OUTLIERS, así que procedemos a eliminar estos registros de la data en general

In [98]:
sinDColumbia = sinDColumbia.drop(sinDColumbia[sinDColumbia['region']=="District of Columbia"].index)

In [99]:
sinDColumbia

,region,fecha,precio,valor_alquiler,tipo_propiedad,roi,valorPIB,año,trimestre,resumenPIB,Id_estado
0,California,2010-02,231512.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL,CA
1,California,2010-03,230640.0,NaN,1Bedroom,NaN,5.8,2010,1,CRECIMIENTO_INERCIAL,CA
2,California,2010-04,230508.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
3,California,2010-05,230649.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
4,California,2010-06,229228.0,NaN,1Bedroom,NaN,4.0,2010,2,CRECIMIENTO_INERCIAL,CA
...,...,...,...,...,...,...,...,...,...,...,...
38908,Wyoming,2019-08,248786.0,1275.0,Sfr,195.126275,5.0,2019,3,CRECIMIENTO_INERCIAL,WT
38909,Wyoming,2019-09,250004.0,1250.0,Sfr,200.003200,5.0,2019,3,CRECIMIENTO_INERCIAL,WT
38910,Wyoming,2019-10,251161.0,1197.5,Sfr,209.737787,6.1,2019,4,CRECIMIENTO_INERCIAL,WT
38911,Wyoming,2019-11,252114.0,1200.0,Sfr,210.095000,6.1,2019,4,CRECIMIENTO_INERCIAL,WT
38912,Wyoming,2019-12,253160.0,1150.0,Sfr,220.139130,6.1,2019,4,CRECIMIENTO_INERCIAL,WT

Creamos el CSV que obtuvimos de la tab la general para así luego enviarlo a un motor MYSQL, y hacer las relaciones correspondientes

In [100]:
pd.DataFrame(sinDColumbia).to_csv('PIB_Estados_tipoVivienda2.csv',index=False)