In [1]:
import pandas as pd

In [2]:
dicc = {'California':'CA','Texas':'TX','New York':'NY','Florida':'FL',
'Illinois':'IL','Pennsylvania':'PA','Ohio':'OH','Michigan':'MI','Georgia':'GA','North Carolina':'NC','New Jersey':'NJ',
'Virginia':'VA','Washington':'WA','Massachusetts':'MA','Indiana':'IN','Arizona':'AZ','Tennessee':'TN','Missouri':'MO',
'Maryland':'MD','Wisconsin':'WI','Minnesota':'MN','Colorado':'CO','Alabama':'AL','South Carolina':'SC','Louisiana':'LA',
'Kentucky':'KY','Oregon':'OR','Oklahoma':'OK','Connecticut':'CT','Iowa':'IA','Mississippi':'MS','Arkansas':'AR','Kansas':'KS',
'Utah':'UT','Nevada':'NV','New Mexico':'NM','West Virginia':'WV','Nebraska':'NE','Idaho':'ID','Hawaii':'HI','Maine':'ME',
'New Hampshire':'NH','Rhode Island':'RI','Montana':'MT','Delaware':'DE','South Dakota':'SD','Alaska':'AK','North Dakota':'ND',
'Vermont':'VT','Wyoming':'WT'}

In [5]:
dicc['California']

'CA'

In [6]:
nombre = list()
id = list()
for i in dicc:
    nombre.append(i)
    id.append(dicc[i])

In [9]:
estados = pd.DataFrame()

In [10]:
estados['ID_Estado'] = id

In [11]:
estados['Estado'] = nombre

In [12]:
estados

   ID_Estado          Estado
0         CA      California
1         TX           Texas
2         NY        New York
3         FL         Florida
4         IL        Illinois
5         PA    Pennsylvania
6         OH            Ohio
7         MI        Michigan
8         GA         Georgia
9         NC  North Carolina
10        NJ      New Jersey
11        VA        Virginia
12        WA      Washington
13        MA   Massachusetts
14        IN         Indiana
15        AZ         Arizona
16        TN       Tennessee
17        MO        Missouri
18        MD        Maryland
19        WI       Wisconsin
20        MN       Minnesota
21        CO        Colorado
22        AL         Alabama
23        SC  South Carolina
24        LA       Louisiana
25        KY        Kentucky
26        OR          Oregon
27        OK        Oklahoma
28        CT     Connecticut
29        IA            Iowa
30        MS     Mississippi
31        AR        Arkansas
32        KS          Kansas
33        UT            Utah
34        NV          Nevada
35        NM      New Mexico
36        WV   West Virginia
37        NE        Nebraska
38        ID           Idaho
39        HI          Hawaii
40        ME           Maine
41        NH   New Hampshire
42        RI    Rhode Island
43        MT         Montana
44        DE        Delaware
45        SD    South Dakota
46        AK          Alaska
47        ND    North Dakota
48        VT         Vermont
49        WT         Wyoming

In [13]:
estados.to_csv('ID_Estados.csv', index=False)